######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 12 13:53:08 2009
######################################################################

QT += dbus maemo5

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp

RESOURCES += widgets.qrc
